# 
# 
#


all: libnegf

.PHONY:  ext_sparskit 

libnegf: ext_sparskit 
	mkdir -p libnegf
	$(MAKE) -C libnegf -f $(SRCDIR)/src/GNUmakefile \
	  ARCH="$(ARCH)" MPI="$(MPI)" INELASTIC="$(INELASTIC)" \
	  FPP="$(FPP)" FPPOPT="$(FPPOPT)" SRCDIR="$(SRCDIR)/src" \
	  FXX="$(FXX)" FXXOPT="$(FXXOPT)" INCLUDES="$(INCLUDES)" 

ext_sparskit:
	mkdir -p sparskit
	$(MAKE) -C sparskit -f $(SRCDIR)/ext_sparskit/GNUmakefile \
	  FXX="$(FXX)" FXXOPT="$(FXXOPT)" SRCDIR="$(SRCDIR)/ext_sparskit"
